(import (micascheme))

(test
  (zx-next test)
  (zx-next mmu)
  (zx-next rgb)
  (zx-next call-frame)
  (zx-next lookup)
  (zx-next tagged)
  (zx-next bit-index)
  (zx-next bank)
  (zx-next bank-table)
  (zx-next bank-alloc)
  (zx-next alloc-pointer)
  (zx-next banked-pointer)
  ;(zx-next allocation)
  (zx-next alloc-banked-pointer)
  (zx-next allocator)
  (zx-next banked-allocator)
  (zx-next alloc)
  (zx-next compiler expr)
  (zx-next scheme alloc)
  (zx-next scheme value)
  (zx-next scheme prims))
