(import (zx-next demo) (zx-next assert) (zx-next regs) (zx-next throw))

(demo
  (catch
    (writeln "testing passing asserts...")

    (ld a #x10)
    (ld bc #x1234)
    (ld de #x5678)
    (ld hl #x9abc)

    ; successes
    (assert a #x10)
    (assert b #x12)
    (assert c #x34)
    (assert d #x56)
    (assert e #x78)
    (assert h #x9a)
    (assert l #xbc)

    (assert bc #x1234)
    (assert de #x5678)
    (assert hl #x9abc)

    (scf) (assert c)
    (rcf) (assert nc)
    (xor a) (assert z)
    (cp 1) (assert nz)

    (writeln "testing failing asserts...")

    (catch (fail))
    (assert c)
    (catch (assert a #xff))
    (assert c)
    (catch (assert b #xff))
    (assert c)
    (catch (assert c #xff))
    (assert c)
    (catch (assert d #xff))
    (assert c)
    (catch (assert e #xff))
    (assert c)
    (catch (assert h #xff))
    (assert c)
    (catch (assert l #xff))
    (assert c)
    (catch (assert bc #xffff))
    (assert c)
    (catch (assert de #xffff))
    (assert c)
    (catch (assert hl #xffff))
    (assert c)
    (catch (scf) (assert nc))
    (assert c)
    (catch (scf) (ccf) (assert c))
    (assert c)
    (catch (xor a) (assert nz))
    (assert c)
    (catch (cp 1) (assert z))
    (assert c)))
