(library (zx-next mmu)
  (export mmu)
  (import
    (zx-next core)
    (zx-next dispatch))

  (define-ops (keywords bc a e)
    ((mmu bc a e)
      (ld bc #x243b)
      (add #x50)
      (out (c) a)
      (ld a e)
      (inc b)
      (out (c) a))
    ((mmu slot a)   (nextreg (fx+ #x50 slot) a))
    ((mmu slot n)   (nextreg (fx+ #x50 slot) n)))
)
