(library (zx-next stackie)
  (export
    const-8
    dup-8
    inc-8 dec-8
    add-8
    mul-8
    const-16
    dup-16
    add-16
    putc)
  (import
    (zx-next core)
    (zx-next write))

  (define-procs
    ((const-8 a)
      (pop hl)
      (push af)
      (inc sp)
      (jp (hl)))
    ((dup-8)
      (pop hl)
      (dec sp)
      (pop de)
      (ld e d)
      (push de)
      (jp (hl)))
    ((inc-8)
      (pop hl)
      (pop de)
      (inc e)
      (push de)
      (jp (hl)))
    ((dec-8)
      (pop hl)
      (pop de)
      (dec e)
      (push de)
      (jp (hl)))
    ((add-8)
      (pop hl)
      (pop de)
      (ld a e)
      (add d)
      (push de)
      (inc sp)
      (jp (hl)))
    ((mul-8)
      (pop hl)
      (pop de)
      (ld a e)
      (mul d e)
      (push de)
      (inc sp)
      (jp (hl)))

    ((const-16 hl)
      (ex de hl)
      (pop hl)
      (push de)
      (jp (hl)))
    ((dup-16)
      (pop hl)
      (pop de)
      (push de)
      (push de)
      (jp (hl)))
    ((inc-16)
      (pop hl)
      (pop de)
      (inc de)
      (push de)
      (jp (hl)))
    ((dec-16)
      (pop hl)
      (pop de)
      (dec de)
      (push de)
      (jp (hl)))
    ((add-16)
      (pop hl)
      (ex de hl)
      (pop hl)
      (pop bc)
      (add hl bc)
      (push hl)
      (ex de hl)
      (jp (hl)))

    ((putc)
      (pop hl)
      (dec sp)
      (pop af)
      (preserve (hl) (call write-char))
      (jp (hl))))
)
