(import (scheme) (check) (any))

(check (any-boolean? any-boolean))
(check (any-char? any-char))
(check (any-string? any-string))
(check (any-fixnum? any-fixnum))
(check (any-flonum? any-flonum))
(check (any-integer? any-integer))
(check (any-type? any-type))
(check (any-lambda? (any-lambda (list any-string any-boolean) any-flonum)))
