(import (scheme) (check) (integer) (char))

(check (equal? (char->ascii #\space) #x20))
(check (equal? (char->ascii (integer->char #xff)) #xff))
(check (equal? (char->ascii (integer->char #x1234)) #x34))

(check (char-newline? #\newline))
(check (not (char-newline? #\a)))

(check (char-space? #\space))
(check (not (char-space? #\a)))

(check (char=? (char colon) #\:))
(check (char=? (char dot) #\.))
(check (char=? (char at-sign) #\@))
(check (char=? (char space) #\space))
(check (char=? (char a) #\a))
(check (char=? (char 0) #\0))
(check (char=? (char :) #\:))
(check (char=? (char (integer 32)) #\space))
(check (char=? (char (integer #x1F600)) #\😀))
(check (char=? (char 😀) #\😀))

(check (equal? (char->datum #\a) 'a))
(check (equal? (char->datum #\space) 'space))
(check (equal? (char->datum #\0) 0))
(check (equal? (char->datum #\.) 'dot))
(check (equal? (char->datum #\;) 'semicolon))
(check (equal? (char->datum #\x0) 'nul))
(check (equal? (char->datum #\x1f) '(integer #x1f)))
(check (equal? (char->datum #\x1F600) '😀))
