(library (fluent)
  (export fluent)
  (import (scheme) (syntax))

  (define-syntax fluent
    (syntax-rules (let values)
      ((fluent expr)
        expr)
      ((fluent (values value ...) (fn arg ...) rest ...)
        (fluent (fn value ... arg ...) rest ...))
      ((fluent expr (let with-var with-expr) rest ...)
        (let ((with-var expr))
          (fluent with-expr rest ...)))
      ((fluent expr (fn arg ...) rest ...)
        (fluent (fn expr arg ...) rest ...)))))
