(library (react-lib)
  (export message osc rect audio mouse-x mouse-y space-pressed? frames)
  (import (micascheme))

  (define-aux-keyword rect)
  (define-aux-keyword message)
  (define-aux-keyword audio)
  (define-aux-keyword osc)
  (define-aux-keyword mouse-x)
  (define-aux-keyword mouse-y)
  (define-aux-keyword space-pressed?)
  (define-aux-keyword frames)
)
