(library (micac expand)
  (export expand-expr)
  (import (micascheme) (micac env) (micac syntax))

  (define (expand-expr $lookup $expr)
    (syntax-case $expr
      (
        cast + - * div
        not and or
        bitwise-not bitwise-and bitwise-ior bitwise-xor
        bitwise-arithmetic-shift-left bitwise-arithmetic-shift-right
        ref &ref)
      ((cast type rhs)
        #`(cast type #,(expand-expr $lookup #'rhs)))
      ((+ arg ...)
        (expand-op2-fold-default $lookup $expr #'0 number? +))
      ((- arg ...)
        (expand-op2-fold $lookup $expr number? -))
      ((* arg ...)
        (expand-op2-fold-default $lookup $expr #'1 number? *))
      ((div arg ...)
        (expand-op2 $lookup $expr number? div))
      ((and arg ...)
        (expand-op2-fold-default $lookup $expr #'#t boolean? and-proc))
      ((or arg ...)
        (expand-op2-fold-default $lookup $expr #'#f boolean? or-proc))
      ((not arg ...)
        (expand-op1 $lookup $expr boolean? not))
      ((bitwise-and arg ...)
        (expand-op2-fold-default $lookup $expr #'-1 integer? bitwise-and))
      ((bitwise-ior arg ...)
        (expand-op2-fold-default $lookup $expr #'0 integer? bitwise-ior))
      ((bitwise-xor arg ...)
        (expand-op2-fold-default $lookup $expr #'0 integer? bitwise-xor))
      ((bitwise-not arg ...)
        (expand-op1 $lookup $expr integer? bitwise-not))
      ((bitwise-arithmetic-shift-left arg ...)
        (expand-op2 $lookup $expr integer? bitwise-arithmetic-shift-left))
      ((bitwise-arithmetic-shift-right arg ...)
        (expand-op2 $lookup $expr integer? bitwise-arithmetic-shift-right))
      ((ref var x ...)
        #`(ref
          #,(expand-expr $lookup #'var)
          #,@(map (partial expand-ref $lookup) (syntaxes x ...))))
      ((&ref var x ...)
        #`(&ref
          #,(expand-expr $lookup #'var)
          #,@(map (partial expand-ref $lookup) (syntaxes x ...))))
      ((id arg ...) (identifier? #'id)
        (switch ($lookup #'id)
          ((false? _)
            #`(id
              #,@(map
                (partial expand-expr $lookup)
                (syntaxes arg ...))))
          ((else $transformer)
            (expand-expr $lookup
              (transform $transformer $expr $lookup)))))
      (id (identifier? #'id)
        (switch ($lookup #'id)
          ((false? _) #'id)
          ((else $transformer)
            (expand-expr $lookup
              (transform $transformer $expr $lookup)))))
      (other #'other)))

  (define (expand-op1 $lookup $syntax $test? $proc)
    (syntax-case $syntax ()
      ((op a)
        (lets
          ($a (expand-expr $lookup #'a))
          ($datum (syntax->datum $a))
          (if ($test? $datum)
            (datum->syntax #'op ($proc $datum))
            #`(op #,$a))))))

  (define (expand-op2 $lookup $syntax $test? $proc)
    (syntax-case $syntax ()
      ((op a b)
        (lets
          ($a (expand-expr $lookup #'a))
          ($b (expand-expr $lookup #'b))
          ($datum-a (syntax->datum $a))
          ($datum-b (syntax->datum $b))
          (if (and ($test? $datum-a) ($test? $datum-b))
            (datum->syntax #'op ($proc $datum-a $datum-b))
            #`(op #,$a #,$b))))))

  (define (expand-op2-fold $lookup $syntax $test? $proc)
    (syntax-case $syntax ()
      ((op a)
        (expand-op1 $lookup $syntax $test? $proc))
      ((op a b)
        (expand-op2 $lookup $syntax $test? $proc))
      ((op a b c cs ...)
        (expand-op2-fold $lookup
          #`(op #,(expand-op2 $lookup #'(op a b) $test? $proc) c cs ...)
          $test? $proc))))

  (define (expand-op2-fold-default $lookup $syntax $default $test? $proc)
    (syntax-case $syntax ()
      ((op) $default)
      ((op a)
        (lets
          ($a (expand-expr $lookup #'a))
          ($datum (syntax->datum $a))
          (if ($test? $datum)
            (datum->syntax #'op ($proc $datum))
            $a)))
      (_ (expand-op2-fold $lookup $syntax $test? $proc))))

  (define (expand-ref $lookup $ref)
    (syntax-case $ref ()
      ((expr) #`(#,(expand-expr $lookup #'expr)))
      (other #'other)))
)
