(import (micascheme))

(test
  (leo2 symbol)
  (leo2 term)
  (leo2 binding)
  (leo2 datum)
  (leo2 equal)
  (leo2 dependent)
  (leo2 evaluate)
  (leo2 reify)
  (leo2 elaborate)
  (leo2 deduce)
  (leo2 lang all)
  (leo2 untyped)
  (leo2 elab))
