(import (micascheme))

(test
  (leo2 symbol)
  (leo2 term)
  (leo2 binding)
  (leo2 datum)
  (leo2 equal)
  (leo2 typed-term)
  (leo2 dependent)
  (leo2 evaluate)
  (leo2 reify)
  (leo2 untyped)
  (leo2 solver)
  (leo2 elaborator)
  (leo2 lang all))
