(import (asm base))

(test
  (asm base)
  (asm data)
  (asm relocable)
  (asm alignment)
  (asm aligned)
  (asm aligned-sized)
  (asm binary)
  (asm identified)
  (asm environment)
  (asm environmental)
  (asm org)
  (asm dependent)
  (asm dependencies)
  (asm size)
  (asm sized)
  (asm sized-relocable)
  (asm sizable)
  (asm size-address)
  (asm block)
  (asm located)
  (asm expression)
  (asm fragment)
  (asm linked)
  (asm assembled)
  (asm block-fragment)
  (asm syntax-expression)
  (asm syntax-block)
  (asm lang)
  (asm ops)
  (asm z80)
  (asm z80-blocks)
  (asm run)
  (asm z80-data))
