(import
  (micascheme)
  (check)
  (labs macro)
  (asm macro-z80))

(define (db $u8)
  (writeln `(db ,$u8)))

(define (db-233 $a $b $c)
  (db (fxior (fxsll $a 6) (fxsll $b 3) $c)))

(define (dw $u16)
  (run-void
    (db (fxand $u16 #xff))
    (db (fxsrl $u16 8))))

(define-macros
  ((ld a i)              (db #xed) (db #x57))
  ((ld a r)              (db #xed) (db #x5f))
  ((ld i a)              (db #xed) (db #x47))
  ((ld r a)              (db #xed) (db #x4f))
  ((ld a (bc))           (db #x0a))
  ((ld a (de))           (db #x1a))
  ((ld a ($nm))          (db #x3a) (dw $nm))
  ((ld (bc) a)           (db #x02))
  ((ld (de) a)           (db #x12))
  ((ld ($nm) a)          (db #x32) (dw $nm))
  ((ld (r $r1) (r $r2))  (db-233 #b01 $r1 $r2))
  ((ld (hl) (r $r))      (db-233 #b01 #b110 $r))
  ((ld (r $r) (hl))      (db-233 #b01 $r #b110))
  ((ld (r $r) $n)        (db-233 #b00 $r #b110) (db $n))
  ((ret)                 (db #xc9)))

(ld a i)
(ld a r)
(ld r a)
(ld i a)

(ld a c)
(ld a d)
(ld d 12)
(ld (hl) h)
(ld a (bc))
(ld a (de))
(ld a (#x1234))
(ld (bc) a)
(ld (de) a)
(ld (#x1234) a)
(ret)
