(import (asm lang) (asm z80) (asm run) (asm asm) (asm asm-core))

(asm-run
  (label loop)
  (di)
  (ld b 0)
  (ld a #b00000010)
  (out (#xfe) a)
  (ld b 0)
  (label loop-1)
  (nop) (nop) (nop) (nop)
  (djnz loop-1)
  (ld a #b00000101)
  (out (#xfe) a)
  (ld b 0)
  (label loop-2)
  (nop) (nop) (nop) (nop)
  (djnz loop-2)
  (jp loop))
