(import (asm-3 base))

(test
  (asm-3 base)
  (asm-3 identified)
  (asm-3 environment)
  (asm-3 environmental)
  (asm-3 org)
  (asm-3 dependent)
  (asm-3 dependencies)
  (asm-3 size)
  (asm-3 sized)
  (asm-3 sized-relocable)
  (asm-3 sizable)
  (asm-3 size-address)
  (asm-3 block)
  (asm-3 located)
  (asm-3 expression)
  (asm-3 fragment)
  (asm-3 assembler)
  (asm-3 assembled)
  (asm-3 block-fragment)
  (asm-3 syntax-expression)
  (asm-3 syntax-block)
  (asm-3 lang))
