(library (c run)
  (export c-run)
  (import (micascheme))

  (define (c-run $string)
    (let ()
      (define $value 0)
      (call-with-output-file "/tmp/main.c"
        (lambda ($port)
          (put-string $port $string))
        `(replace))
      (system "gcc /tmp/main.c -o /tmp/main -lsdl2 -Wno-parentheses-equality")
      (system "rm /tmp/main.c")
      (set! $value (system "/tmp/main"))
      (system "rm /tmp/main")
      $value))
)
