(import (micascheme))

(test
  (tico binding)
  (tico block)
  (tico compilation)
  (tico constant)
  (tico datum)
  (tico entry)
  (tico evaluation)
  (tico expression)
  (tico layment)
  (tico layout)
  (tico parameter)
  (tico path)
  (tico reader)
  (tico value)
  (tico tico)
  (tico type)
  (tico typing)
  (tico variable))
