(import (micascheme))

(test
  (tico binding)
  (tico compilation)
  (tico compiled)
  (tico compiler)
  (tico constant)
  (tico datum)
  (tico evaluation)
  (tico expression)
  (tico typed-expression)
  (tico packet)
  (tico reader)
  (tico value)
  (tico type)
  (tico typed)
  (tico variable))
