(import (micascheme))

(test
  (tico binding)
  (tico compilation)
  (tico constant)
  (tico datum)
  (tico dependency)
  (tico entry)
  (tico evaluation)
  (tico expression)
  (tico global)
  (tico layment)
  (tico layout)
  (tico packet)
  (tico parameter)
  (tico path)
  (tico reader)
  (tico value)
  (tico tico)
  (tico type)
  (tico typing)
  (tico variable))
