(import (micascheme))

(test
  (leo datum)
  (leo compiler)
  (leo decompiler)
  (leo evaluator)
  (leo parser)
  (leo reader)
  (leo mica all)
  (leo fragment)
  (leo getter)
  (leo writing-reader)
  (leo quotify)
  (leo code)
  (leo write)
  (leo test)
  (leo transform)
  (leo library)
  (leo syntax-error)
  (leo expand)
  (leo scheme)
  (leo path)
  (leo source-file-descriptor)
  (leo read)
  (leo language)
  (leo load))
