(library (leo definer)
  (export definer)
  (import
    (except (scheme) syntax-error)
    (leo syntax-error)
    (leo lookup)
    (syntax))

  (define-syntax (definer $syntax)
    (lambda (lookup?)
      (syntax-case $syntax ()
        ((_ (id . x))
          (safe-lookup? lookup? #'id #'definer)
          (lookup? #'id #'definer)))))
)
