(import (micascheme) (getter) (leo getter))

(check-gets atom/eof-getter "" eof 0)
(check-gets atom/eof-getter "foo" 'foo 3)
(check-gets atom/eof-getter "foo bar" 'foo 3)
(check-gets atom/eof-getter "foo-bar! bar" 'foo-bar! 8)
(check-gets atom/eof-getter "foo: bar" 'foo: 4)
(check-gets atom/eof-getter "123 bar" 123 3)
(check-gets atom/eof-getter "+123 bar" +123 4)
(check-gets atom/eof-getter "-123 bar" -123 4)
(check-gets atom/eof-getter "3.14 bar" 3.14 4)
(check-gets atom/eof-getter "\"foo\" bar" "foo" 5)

(check-get-raises atom/eof-getter " foo bar")
(check-get-raises atom/eof-getter "() bar")
(check-get-raises atom/eof-getter "(foo) bar")
(check-get-raises atom/eof-getter "#t bar")

(check-gets line/eof-getter "" eof 0)
(check-gets line/eof-getter "123\n" 123 4)
(check-gets line/eof-getter "\"foo\"\n" "foo" 6)
(check-gets line/eof-getter "foo\n" 'foo 4)
(check-gets line/eof-getter "foo bar\n" '(foo bar) 8)
(check-gets line/eof-getter "foo bar goo\n" '(foo (bar goo)) 12)

(check-get-raises line/eof-getter "123 ")

(check-gets script-getter "" '() 0)
(check-gets script-getter "10\n" '(10) 3)
(check-gets script-getter "10\n20\n" '(10 20) 6)
(check-gets script-getter "foo\nfoo bar\n" '(foo (foo bar)) 12)

(check-gets indent?-getter "" #f 0)
(check-gets indent?-getter "abc" #f 0)
(check-gets indent?-getter "\t" #f 0)
(check-gets indent?-getter "  " #t 2)
(check-gets indent?-getter "  abc" #t 2)
(check-get-raises indent?-getter " abc")
(check-get-raises indent?-getter " \t")
