#!/bin/bash
LEO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$LEO_DIR/.."
LIB_DIR="$BASE_DIR/lib"
SCHEME_DIR="$LIB_DIR/scheme"

exec "$SCHEME_DIR/bin/scheme" \
    -b "$SCHEME_DIR/lib/petite.boot" \
    -b "$SCHEME_DIR/lib/scheme.boot" \
    --libdirs ".:$LIB_DIR/micascheme" \
    --program "$LIB_DIR/leo.so" \
    "$@"
