(library (leo let)
  (export
    let letrec let-values
    let* letrec* let*-values
    let-syntax letrec-syntax)
  (import
    (rename (scheme)
      (let %let)
      (letrec %letrec)
      (let-values %let-values)
      (let* %let*)
      (letrec* %letrec*)
      (let*-values %let*-values)
      (let-syntax %let-syntax)
      (letrec-syntax %letrec-syntax))
    (syntax-keywords)
    (leo with)
    (leo keywords)
    (keyword)
    (syntax)
    (syntaxes))

  (define-rules-syntaxes
    (keywords with values in)

    ((let (name (id expr) ... (in x xs ...)))
      (keyword? name)
      (%let name ((id expr) ...) x xs ...))
    ((let binding ... (in x xs ...))
      (%let (binding ...) x xs ...))
    ((let* binding ... (in x xs ...))
      (%let* (binding ...) x xs ...))
    ((letrec binding ... (in x xs ...))
      (%letrec (binding ...) x xs ...))
    ((letrec* binding ... (in x xs ...))
      (%letrec* (binding ...) x xs ...))
    ((let-values (with (values id ...) expr) ... (in x xs ...))
      (%let-values (((id ...) expr) ...) x xs ...))
    ((let*-values (with (values id ...) expr) ... (in x xs ...))
      (%let*-values (((id ...) expr) ...) x xs ...))
    ((let-syntax binding ... (in x xs ...))
      (%let-syntax (binding ...) x xs ...))
    ((letrec-syntax binding ... (in x xs ...))
      (%letrec-syntax (binding ...) x xs ...))

    ; TODO: Phase these out.
    ((let (name (with binding ...) x xs ...))
      (keyword? name)
      (%let name (binding ...) x xs ...))
    ((let (with binding ...) x xs ...)
      (%let (binding ...) x xs ...))
    ((let* (with binding ...) x xs ...)
      (%let* (binding ...) x xs ...))
    ((letrec (with binding ...) x xs ...)
      (%letrec (binding ...) x xs ...))
    ((letrec* (with binding ...) x xs ...)
      (%letrec* (binding ...) x xs ...))
    ((let-values (with (with (values id ...) expr) ...) x xs ...)
      (%let-values (((id ...) expr) ...) x xs ...))
    ((let*-values (with (with (values id ...) expr) ...) x xs ...)
      (%let*-values (((id ...) expr) ...) x xs ...))
    ((let-syntax (with binding ...) x xs ...)
      (%let-syntax (binding ...) x xs ...))
    ((letrec-syntax (with binding ...) x xs ...)
      (%let-syntax (binding ...) x xs ...)))
)
