(library (leo let)
  (export let)
  (import
    (rename (scheme) (let %let))
    (syntax-keywords)
    (leo with)
    (leo in)
    (leo recursive)
    (leo sequential)
    (keyword)
    (syntax)
    (syntaxes))

  (define-rules-syntaxes
    (keywords with values recursive sequential syntax in)

    ((let (with (values id ...) expr) ... (in x xs ...))
      (let-values (((id ...) expr) ...) x xs ...))
    ((let (sequential (recursive binding ... (in x xs ...))))
      (letrec* (binding ...) x xs ...))
    ((let (sequential (with (values id ...) expr) ... (in x xs ...)))
      (let*-values (((id ...) expr) ...) x xs ...))
    ((let (sequential binding ... (in x xs ...)))
      (let* (binding ...) x xs ...))
    ((let (recursive (syntax binding ... (in x xs ...))))
      (let-syntax (binding ...) x xs ...))
    ((let (recursive binding ... (in x xs ...)))
      (letrec (binding ...) x xs ...))
    ((let (syntax binding ... (in x xs ...)))
      (let-syntax (binding ...) x xs ...))
    ((let (name binding ... (in x xs ...)))
      (keyword? name)
      (%let name (binding ...) x xs ...))
    ((let binding ... (in x xs ...))
      (%let (binding ...) x xs ...)))
)
