(library (leo maker)
  (export maker)
  (import
    (scheme)
    (identifier))

  (define-syntax (maker $syntax)
    (lambda (lookup?)
      (syntax-case $syntax ()
        ((_ (target id))
          (lookup? #'target #'maker)
          ((lookup? #'target #'maker) #'id))
        ((_ id)
          (identifier-append #'id #'make #'- #'id)))))
)
