(library (leo setter!)
  (export setter!)
  (import
    (scheme)
    (identifier)
    (leo lookup))

  (define-syntax (setter! $syntax)
    (lambda (lookup?)
      (syntax-case $syntax ()
        ((_ (target id))
          (safe-lookup? lookup? #'target #'setter!)
          ((lookup? #'target #'setter!) #'id))
        ((_ (target id))
          (identifier-append #'target #'target #'- #'id #'- #'set!)))))
)
