(import (micascheme))

(test
  (asm-2 label)
  (asm-2 relocable)
  (asm-2 alignment)
  (asm-2 aligned)
  (asm-2 alignable)
  (asm-2 aligned-sized)
  (asm-2 block)
  (asm-2 fragment)
  (asm-2 local)
  (asm-2 block-fragment)
  (asm-2 linked)
  (asm-2 linker)
  (asm-2 lang)
  (asm-2 core)
  (asm-2 z80))
