(import (asm-2 lang) (asm-2 z80) (asm-2 run))

(run
  (label loop)
  (di)
  (ld b 0)
  (ld a #b00000010)
  (out (#xfe) a)
  (ld b 0)
  (label loop-1)
  (nop) (nop) (nop) (nop)
  (djnz loop-1)
  (ld a #b00000101)
  (out (#xfe) a)
  (ld b 0)
  (label loop-2)
  (nop) (nop) (nop) (nop)
  (djnz loop-2)
  (jp loop))
