(library (emu zx-spectrum-48 rom)
  (export define-zx-spectrum-48-rom)
  (import (scheme) (syntax) (emu z80 rom) (emu z80 asm))

  (define-rule-syntax (define-zx-spectrum-48-rom id)
    (define-z80-rom (id #x4000)
      (ld a #\H)
      (out (#x34) a)
      (ld a #\i)
      (out (#x34) a)
      (ld a #\!)
      (out (#x34) a)
      (ld a #\newline)
      (out (#x34) a)
      (halt)))
)
