(library (labs syntax)
  (export syntax-flatten)
  (import (micascheme))

  (define (syntax-flatten $syntax)
    (syntax-case $syntax (begin)
      ((begin $body ...)
        (syntax->list #'($body ...)))
      ($other (list #'$other))))
)
