.TH LEO 1 "March 2026" "0.1.26" "Leo Scheme Language Manual"
.SH NAME
leo \- high-performance JIT-based execution environment for the Leo Scheme language
.SH SYNOPSIS
.B leo
[\fIoptions\fR] [\fIfile\fR [\fIargs\fR]]
.SH DESCRIPTION
.B leo
is the primary command-line interface for the Leo Scheme programming language. It
functions as an interpreter that utilizes a Just-In-Time (JIT) compiler to
dynamically optimize and execute code on the fly.
.PP
If a
.I file
is provided, it is executed with any subsequent
.I args
passed to the script. If no file is provided and no options are specified, the
program exits.
.SH OPTIONS
.TP
.BR \-v ", " \-\-version
Show version information and exit.
.TP
.BR \-h ", " \-\-help
Show a help message and exit.
.SH ARGUMENTS
.TP
.I file
The source file to be executed.
.TP
.I args
Optional arguments passed directly to the script being executed.
.SH EXIT STATUS
.TP
.B 0
Success. The file was executed or an information option was displayed.
.TP
.B 1
Failure. A syntax error, runtime exception, or invalid option occurred.
.SH SEE ALSO
.BR scheme (1),
.SH AUTHOR
Developed by Michał Pociecha-Łoś.
