(import (zx-next scheme demo))

(demo
  (write #t)
  (put-char #\return)
  (write #f)
  (put-char #\return)
  (write "foo")
  (put-char #\return)
  (write 'foo)
  (put-char #\return)
  (write #x12)
  (put-char #\return)
  (write #x1234)
  (put-char #\return)
  (write #\a)
  (put-char #\return)
  (write '())
  (put-char #\return)
  (write (cons #\a (cons "foo" 'bar)))
  (put-char #\return)
  (write (cons #\a (cons "foo" (cons 'bar '()))))
  (put-char #\return))
