(library (tt string)
  (export string-length string=? string+ join-string list->string string->list number->string)
  (import
    (tt lang)
    (tt number)
    (tt list)
    (prefix (scheme) %)
    (prefix (procedure) %))

  (define string=? (unchecked (pi (string string) boolean) %string=?))
  (define string-length (unchecked (pi (string) number) %string-length))
  (define string+ (unchecked (pi (string string) string) %string-append))
  (define list->string (unchecked (pi ((list char)) string) %list->string))
  (define string->list (unchecked (pi (string) (list char)) %string->list))
  (define join-string (unchecked (pi ((list string)) string) (%partial %apply %string-append)))
  (define number->string (unchecked (pi (number) string) %number->string))
)
