(library (zexy math)
  (export band bor shl shr msb lsb inc-nm)
  (import (micascheme))

  (define-syntax bor (identifier-syntax bitwise-ior))
  (define-syntax band (identifier-syntax bitwise-and))
  (define-syntax shl (identifier-syntax bitwise-arithmetic-shift-left))
  (define-syntax shr (identifier-syntax bitwise-arithmetic-shift-right))
  (define (msb $nm) (band (shr $nm 8) #xff))
  (define (lsb $nm) (band $nm #xff))
  (define (inc-nm $nm) (band (add1 $nm) #xffff))
)
