(library (micalog micac)
  (export micalog-emu)
  (import
    (prefix (micascheme) %)
    (micalog micac transformer)
    (micalog core type)
    (micac syntax-c)
    (micac expand)
    (micalog micac on-old-new)
    (micalog micac inits-updates)
    (micac lib emu)
    (micalog verilog)
    (micalog keywords)
    (only (micac) var)
    (only (micac run) micac-run-echo?)
    (only (c run) c-run-echo?))
  (%export (import (micalog keywords)))
  (%export (import (only (micac lib emu) red green blue video-x video-y mouse-x mouse-y mouse-pressed?)))

  (%define-case-syntax (micalog-emu micalog)
    (%quasisyntax
      (%parameterize ((c-run-echo? #t) (micac-run-echo? #t))
        (display-verilog micalog)
        (%newline)
        (%unsyntax
          (%fluent (%syntax micalog)
            (module->typed-syntax)
            (module->on-old-new-syntax)
            (module->inits-updates-syntax)
            (module->micac))))))
)
