game:
  title: "Leo Game"
  size:
    width: 480
    height: 256
  stack:
    point: position:
      x: 10
      y: 20
    filled rectangle:
      position:
        x: 10
        y: 20
      size:
        width: 30
        height: 40
    sprite
      image: "depressedChicken.png"
      position
        x: 32
        y: 64
      anchor
        x: 32
        y: 32
      size:
        width: 32
        height: 32
  animation: empty




